hortonworks/streamline

- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/kafka/StreamlineEventSerializer.java
- streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/kafka/StreamlineEventSerializerTest.java
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/SinkNodeForm.jsx
Change-Id: I16298b2500c43c831617b5a9cfbe8caf46d718f3
> STREAMLINE-666: Use schema registered by UI to serialize kafka messages

- bootstrap/bootstrap.sh
- bootstrap/sql/mysql/create_tables.sql
- bootstrap/sql/mysql/drop_tables.sql
- bootstrap/sql/phoenix/create_tables.sql
- bootstrap/sql/phoenix/drop_tables.sql
- bootstrap/sql/postgresql/create_tables.sql
- bootstrap/sql/postgresql/drop_tables.sql
- bootstrap/users_roles/user_anon.json
- streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/catalog/User.java
- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/TopologyEditorToolbar.java
- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/service/StreamCatalogService.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/StreamsModule.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyEditorToolbarResource.java
Right now it stores with a dummy user id, changes needs to be made once https://github.com/hortonworks/streamline/pull/521 is merged to populate the actual user id.
> STREAMLINE-733: Metadata API for TopologyEditor component bar

- common/pom.xml
- conf/streamline-dev.yaml
- conf/streamline.mysql.yaml
- conf/streamline.phoenix.yaml
- conf/streamline.postgre.yaml
- conf/streamline.yaml
- docs/SECURITY.md
- pom.xml
- registries/dashboard-registry/pom.xml
- storage/core/pom.xml
- webservice/pom.xml
- webservice/src/main/java/com/hortonworks/streamline/webservice/StreamlineApplication.java
- webservice/src/main/java/com/hortonworks/streamline/webservice/StreamlineConfiguration.java
- Add servlet filter to Dropwizard application environment
- Add servlet filter configuration to yaml files
- Fix registry/common dependencies in YAML file
> STREAMLINE-710: Spnego kerberos Filter for Streamline

- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/StormTopologyDependenciesHandler.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/NotifierInfoCatalogResource.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/UDFCatalogResource.java
Added 'streamline-functions' and 'notifiers' prefix while storing the udfs and notifiers.
> STREAMLINE-739: Embed jar name along with UUID

- streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/JoinBoltFluxComponent.java
- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/WindowedQueryBolt.java
- streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/TestWindowedQueryBolt.java
- streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/WindowedQueryBolt_TestTopology.java
Core logic from WindowedQueryBolt has been moved into Storm's JoinBolt.
WindowedQueryBolt in Streamline has now become an adapter for Storm's JoinBolt... providing any StreamLine specific customizations
> STREAMLINE-702  Factoring out join functionality from WindowedQueryBolt

- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/Constants.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/DruidSinkBundleHintProvider.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/discovery/ambari/ServiceConfigTypeAmbariToOriginalPattern.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/discovery/ambari/ServiceConfigurations.java
Just a simple patch to activate auto import Druid service for Ambari import.
@harshach Please review and comment. If we want more than providing hint for Druid sink, please let me know which information we need to have. Thanks in advance.
> STREAMLINE-780 Import Druid for auto import from Ambari

- common/src/main/java/com/hortonworks/streamline/common/Constants.java
- common/src/main/java/com/hortonworks/streamline/common/security/authenticator/AbstractLogin.java
- common/src/main/java/com/hortonworks/streamline/common/security/authenticator/KerberosLogin.java
- common/src/main/java/com/hortonworks/streamline/common/security/authenticator/Login.java
- common/src/main/java/com/hortonworks/streamline/common/util/Shell.java
- common/src/main/java/com/hortonworks/streamline/common/util/Utils.java
- conf/streamline-dev.yaml
- conf/streamline.yaml
- conf/streamline_jaas.conf
- streamline-dist/src/main/assembly/binary.xml
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/SchemaResource.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/StreamsModule.java
- webservice/src/main/java/com/hortonworks/streamline/webservice/LoginConfiguration.java
- webservice/src/main/java/com/hortonworks/streamline/webservice/StreamlineApplication.java
- webservice/src/main/java/com/hortonworks/streamline/webservice/StreamlineConfiguration.java
- webservice/src/test/resources/streamline-test.yaml
Change-Id: Ic7305da68a12d6fee19e76e392ea483bdb7847df
> STREAMLINE-764: Kerberos login and relogin thread for streamline server

- common/src/main/java/com/hortonworks/streamline/common/Constants.java
- common/src/main/java/com/hortonworks/streamline/common/util/WSUtils.java
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/TopologyActions.java
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/container/TopologyActionsContainer.java
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyActionsService.java
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/state/TopologyContext.java
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/state/TopologyStates.java
- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/topology/component/TopologyExportVisitor.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/container/NamespaceAwareContainer.java
- streams/common/src/main/java/com/hortonworks/streamline/streams/common/Constants.java
- streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/TopologyLayoutConstants.java
- streams/metrics/src/main/java/com/hortonworks/streamline/streams/metrics/container/TopologyMetricsContainer.java
- streams/metrics/src/main/java/com/hortonworks/streamline/streams/metrics/topology/TopologyMetrics.java
- streams/metrics/src/main/java/com/hortonworks/streamline/streams/metrics/topology/TopologyTimeSeriesMetrics.java
- streams/metrics/src/main/java/com/hortonworks/streamline/streams/metrics/topology/service/TopologyMetricsService.java
- streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java
- streams/runners/storm/common/src/main/java/com/hortonworks/streamline/streams/storm/common/StormJaasCreator.java
- streams/runners/storm/common/src/main/java/com/hortonworks/streamline/streams/storm/common/StormRestAPIClient.java
- streams/runners/storm/common/src/main/java/com/hortonworks/streamline/streams/storm/common/StormTopologyUtil.java
- streams/runners/storm/common/src/main/resources/storm_jaas.config_template
- streams/runners/storm/metrics/src/main/java/com/hortonworks/streamline/streams/metrics/storm/topology/StormTopologyMetricsImpl.java
- streams/runners/storm/metrics/src/main/java/com/hortonworks/streamline/streams/metrics/storm/topology/StormTopologyTimeSeriesMetricsImpl.java
- streams/runners/storm/metrics/src/test/java/com/hortonworks/streamline/streams/metrics/storm/topology/StormTopologyTimeSeriesMetricsImplTest.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/CatalogResourceUtil.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/MetricsResource.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/NamespaceCatalogResource.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/SearchCatalogResource.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyCatalogResource.java
- streams/service/src/test/java/com/hortonworks/streamline/streams/service/NamespaceCatalogResourceTest.java
* Create jaas config file for secured Storm cluster before submitting topology
* Pass jass and other configurations regarding security when submitting topology
* currently WIP: Topology doesn't work due to CNFE: AutoHDFS
This is currently WIP, but I'd like to get this reviewed to confirm I'm on the right way.
This patch is relying on Ambari specific configuration (nimbus principal) to get Nimbus service name, so doesn't work with non-Ambari based secured Storm clusters. For now, I'm not clear how we can address non-Ambari cluster as well, but if it should be addressed as well, I'd like to handle it from another JIRA issue.
This patch assumes that Streamline is launched with JAAS config. `keytab` and `principal` in Storm JAAS file will be from `StreamlineServer` entry. Please refer …
> STREAMLINE-763 Topology should be able to deployed on Secured Storm cluster

- common/src/main/java/com/hortonworks/streamline/common/exception/service/exception/request/EntityNotFoundException.java
- streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/catalog/User.java
- streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/impl/DefaultStreamlineAuthorizer.java
- streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/impl/NoopAuthorizer.java
- streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/service/SecurityCatalogResource.java
- streams/sdk/src/main/java/com/hortonworks/streamline/streams/security/StreamlineAuthorizer.java
@shahsank3t , you can test it with "GET api/v1/catalog/users/current" in secure mode.
> STREAMLINE-782: Need an API to get current user when in secure mode

- bootstrap/services/storm-bundle.json
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/StormServiceRegistrar.java
- streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/register/impl/StormServiceRegistrarTest.java
This patch is on top of STREAMLINE-763.
> STREAMLINE-785 Add optional field 'nimbus principal' to manual Storm cluster registration

- streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/impl/DefaultStreamlineAuthorizer.java
> Issue-591: Add metadata for Admin role during server start

- common/src/main/java/com/hortonworks/streamline/common/util/WSUtils.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyCatalogResource.java
It came from misunderstanding of SecurityContext: isSecure().
It determines whether HTTP connection is secured (HTTPS) or not, not Streamline is run in kerberized environment or not.
> Quick Fix: fix the logic for getting user name from principal

- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/AbstractKafkaBundleHintProvider.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/AbstractSecureBundleHintProvider.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/ComponentBundleHintProvider.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/KafkaBundleHintProvider.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/KafkaSinkBundleHintProvider.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/StormBundleHintProvider.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/HBaseMetadataService.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/HiveMetadataService.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/KafkaMetadataService.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/StormMetadataService.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/common/EnvironmentServiceUtil.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/json/KafkaBrokersInfo.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/json/Keytabs.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/json/Principals.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/json/Security.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/json/ServicePrincipal.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/json/UserPrincipal.java
- streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/AbstractKafkaBundleHintProviderTest.java
- streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/service/metadata/KafkaMetadataServiceTest.java
- streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/service/metadata/StormMetadataServiceTest.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/StreamsModule.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/metadata/StormMetadataResource.java
@harshach This PR has the 3 commits, one per issue. I rebased it on top of master, and did mvn clean install. All tests passed for me. I also tested with secure and insecure mode, as well as the hints. The only thing I didn't test was the StormHintProvider because I don't really know all the intricacies of bundling that hint provider with the UI. I believe @shahsank3t is supposed to do this. IF not let me know and I will look into it.
> ISSUE-593, ISSUE-594, ISSUE-595

- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/service/StreamCatalogService.java
- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/topology/component/TopologyExportVisitor.java
> ISSUE-609 Added export/import of projection processor

- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/Projection.java
- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/TopologyRule.java
- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/service/StreamCatalogService.java
> ISSUE-613: Cloning projection processors with respective configuration as part of Rule

- streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java
Change-Id: I996576db56c9b4f6a459ddfbbe4b76f098e2703d
> ISSUE-619: Fix empty map for clustersSecurityConfig

- streams/service/src/main/java/com/hortonworks/streamline/streams/service/SearchCatalogResource.java
> ISSUE-625: Service pool sorting by name should be case insensitive

- bootstrap/components/sinks/kafka-sink-topology-component.json
- streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/KafkaBoltFluxComponent.java
- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/kafka/StreamlineEventToKafkaMapper.java
Change-Id: Ibd9c4e219175ff6729a98656b829255c3772824d
> ISSUE-629: Make keyField and keySerializer optional for kafka sink

- bootstrap/components/sinks/hbase-sink-topology-component.json
- streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/TopologyLayoutConstants.java
- streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/HbaseBoltFluxComponent.java
- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/hbase/StreamlineEventHBaseMapper.java
Change-Id: I9df398a3caf269cbfcd67bab369fd9d0a490ba46
> ISSUE-643: Expose row key for hbase sink

- bootstrap/components/topology/storm-topology-component.json
* topology.worker.childopts will be appended to the worker.childopts from Storm side
> ISSUE-653 Replace worker.childopts with topology.worker.childopts

- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/kafka/StreamlineEventSerializer.java
> ISSUE-666 Make kafka streamline event serializer not dependent on registry API.

- bootstrap/bootstrap-udf.sh
- streams/functions/src/main/java/com/hortonworks/streamline/streams/udaf/LongCount.java
> ISSUE-688: Sum and Count UDAF does not work with nested fields

- bootstrap/bootstrap-notifiers.sh
- streams/notifier/src/main/java/com/hortonworks/streamline/streams/notifiers/ConsoleNotifier.java
> ISSUE-715: Fix name and description for email and console notifiers

- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/spout/JsonFileReader.java
- streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/hdfs/TestJsonFileReader.java
> BUG-82177 - Fixing NullPtrException in HdfsSpouts JsonFileReader

- bootstrap/components/sinks/hdfs-sink-topology-component.json
> BUG-82180 - HdfsSink : Change UI display name "Count policy value" to "Flush Count"

- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/model/StreamlineJPMMLModelRunner.java
…om input schema
- Processor output fields including input fields plus ML (PMML) model fields
Change-Id: I84ddc9069296f023ddee399c038c761b58a740e4
> STREAMLINE-790: PMML Processor Needs to enhanced to pass on fields from input schema

- streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/service/StreamCatalogService.java
Update the right notifier jar file name in the notifier config during a import.
Fixes #726
> ISSUE-726: Imported topology containing a notifier fails during deployment

- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/container/TopologyActionsContainer.java
- streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/TopologyLayoutConstants.java
- streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java
Closes #728 
@harshach Please review. Thanks in advance.
> ISSUE-728 pass nimbus.thrift.max_buffer_size from Environments/Storm during the deployment

- bootstrap/components/processors/console_custom_processor.json
- streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/CustomProcessorBoltFluxComponent.java
* console custom processor doesn't seem to conform new interface
* add verification for new field
@priyank5485 Please review this. Thanks in advance.
> Simple fix to Custom Processor

- conf/streamline-dev.yaml
- conf/streamline.mysql.yaml
- conf/streamline.phoenix.yaml
- conf/streamline.postgre.yaml
- conf/streamline.yaml
- streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java
* add three options: proxyUrl, proxyUsername, proxyPassword
* requires Storm cluster which includes STORM-2598
Please refer the changes of STORM-2598: https://github.com/apache/storm/pull/2175/files
This closes #754
> ISSUE-754: Streamline artifacts fetch via proxy server

- common/src/main/java/com/hortonworks/streamline/common/exception/service/exception/server/StreamingEngineNotReachableException.java
- streams/runners/storm/common/src/main/java/com/hortonworks/streamline/streams/storm/common/StormRestAPIClient.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyCatalogResource.java
* Show error and block deleting topology if topology is running
* or can't reach underlying streaming engine
This closes #777.
> ISSUE-777 Prevent deleting topology if topology is running

- common/src/main/java/com/hortonworks/streamline/common/util/WSUtils.java
- streams/runners/storm/common/src/main/java/com/hortonworks/streamline/streams/storm/common/StormRestAPIClient.java
Modified StormRestAPIClient to encode parts of the url.
Fixes #783
> ISSUE-783: Putting a special character like question mark in any processor name causes exception in App Deployment

- streams/runners/storm/common/src/main/java/com/hortonworks/streamline/streams/storm/common/StormRestAPIClient.java
> ISSUE-786 Cleanup api for managing storm topologies

- webservice/src/main/resources/app/scripts/containers/Configuration/CustomProcessorForm.jsx
- webservice/src/main/resources/app/styles/css/graph-style.css
> ISSUE-739 CSS fixes for Microsoft Edge browser 

- webservice/src/main/resources/custom_error_pages/401.html
This close #740 
currently, we are showing ref screenshot below:-
> ISSUE-740 Streamline initial screen in secure mode

- webservice/src/main/resources/app/scripts/app.js
- webservice/src/main/resources/app/scripts/app_state.js
- webservice/src/main/resources/app/scripts/components/Header.jsx
- webservice/src/main/resources/app/scripts/components/UnKnownAccess.jsx
- webservice/src/main/resources/app/scripts/rest/MiscREST.js
- webservice/src/main/resources/app/scripts/utils/Constants.js
This PR contains UI side changes for https://github.com/hortonworks/streamline/issues/745
> ISSUE-745 Add logout link to invalidate the kerberos auth cookie (UI)

- bootstrap/components/sinks/kafka-sink-topology-component.json
- bootstrap/components/sources/kafka-source-topology-component.json
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/SchemaResource.java
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/SinkNodeForm.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/SourceNodeForm.jsx
- webservice/src/main/resources/app/scripts/libs/form/Fields.jsx
- webservice/src/main/resources/app/scripts/rest/TopologyREST.js
- webservice/src/main/resources/app/scripts/utils/Utils.js
Change-Id: Ieb8b2195f51018ed97a39993c8719da07faac982
> ISSUE-774: Make reader and writer schema version mandatory for kafka

- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/StatusImpl.java
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/TopologyActions.java
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/state/TopologyStates.java
Kill any running instance of topology in case the deployment throws Exceptions but topology starts running in the cluster
Fixes #802
> ISSUE-802: Streaming Analytics Manager Application status issue

- webservice/src/main/resources/app/scripts/containers/Configuration/CustomProcessorContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Configuration/CustomProcessorForm.jsx
- webservice/src/main/resources/app/scripts/rest/CustomProcessorREST.js
- webservice/src/main/resources/app/scripts/utils/Utils.js
This PR contains UI side changes for #801
> ISSUE-801 Handle errors during custom processor upload

- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/discovery/ambari/AmbariRestAPIConstants.java
- streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/discovery/ambari/AmbariServiceNodeDiscoverer.java
- streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/HiveBoltFluxComponent.java
- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/StreamlineHiveMapper.java
1). Improve logic to fetch latest ambari configs
2). Fix minor issue in HiveBoltFluxComponent
3). Pass lowercase field name strings to DelimitedInputWriter in StreamlineHiveMapper
> ISSUE-810: Fix the issues observed during Hive Sink testing

- CHANGELOG.md
- streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/AvroStreamsSnapshotDeserializerTest.java
Change-Id: Ic782797a78708d65a0a1c7c820e0ae7a3e0cf750
> ISSUE-833: Fix failing AvroStreamsSnapshotDeserializerTest

- streams/runners/storm/runtime/pom.xml
- streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/rules/FunctionsTest.java
- streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/rules/WindowRulesBoltTest.java
- streams/runners/storm/runtime/src/test/resources/streamline-udaf.json
- streams/runners/storm/runtime/src/test/resources/streamline-udf.json
> ISSUE-838: Unit tests to cover UDFs and UDAFs shipped with streamline

- webservice/src/main/resources/app/scripts/components/TopologyGraphComponent.jsx
- webservice/src/main/resources/app/scripts/components/ZoomPanelComponent.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TestRunComponents/TestSourceNodeModal.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/TopologyEditorContainer.jsx
This fixes https://github.com/hortonworks/streamline/issues/853 and both the sub tasks mention in it.
> Issue-853: Enable Application Test mode from UI

- bootstrap/components/sinks/kafka-sink-topology-component.json
- streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/KafkaBoltFluxComponent.java
> ISSUE-863 Expose serdes.protocol.version property to user in kafka sink.

- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/TopologyEditorContainer.jsx
- webservice/src/main/resources/app/styles/css/style.css
> ISSUE-860 UI Add timeout option to topology test run

- webservice/src/main/resources/app/scripts/components/NotesForm.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/SinkNodeForm.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/SourceNodeForm.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/TopologyEditorContainer.jsx
1] Clicking on test case itself test case dialog is shown to configure OR edit.
2] while double clicking on the source, processors, and sink the node configuration is shown in non-editable mode.
> BUG-87346 Test mode: few minor UI issues

- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyTestRunner.java
- streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/component/impl/testing/TestRunSink.java
- streams/runners/storm/actions/src/test/java/com/hortonworks/streamline/streams/actions/storm/topology/TestTopologyDagCreatingVisitorTest.java
- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/testing/TestRunSinkBolt.java
This closes #887
* just remove logging events from Sink
Change-Id: I5bfec56e4ac151e1056a59f90faca30f3b7f53d4
> ISSUE-887 Recording events from sink leads the result confused

- webservice/src/main/resources/app/scripts/components/EditorGraph.jsx
- webservice/src/main/resources/app/scripts/components/TopologyGraphComponent.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TestRunComponents/EventLogContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TestRunComponents/TestSourceNodeModal.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/ComponentNodeContainer.js
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/TopologyEditorContainer.jsx
- webservice/src/main/resources/app/scripts/rest/TestRunREST.js
- webservice/src/main/resources/app/styles/css/style.css
This PR for multiple issues because all are inter-related.
Issue addressed in this PR are below 
1] ISSUE-899
2] ISSUE-902
3] ISSUE-901
> Test mode UI changes

- bootstrap/components/sinks/hdfs-sink-topology-component.json
- bootstrap/components/sinks/hive-sink-topology-component.json
- bootstrap/components/sinks/jdbc-sink-topology-component.json
- webservice/src/main/resources/app/scripts/containers/Configuration/AppRoleForm.jsx
- webservice/src/main/resources/app/scripts/containers/Configuration/UserForm.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/ProjectionProcessorContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/TopologyEditorContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/WindowingAggregateNodeForm.jsx
- webservice/src/main/resources/app/scripts/libs/form/Fields.jsx
- webservice/src/main/resources/app/scripts/utils/ProcessorUtils.js
Select All options functionality to other processors & sinks, which allows the user to add multiple input fields.
@shahsank3t  please review the same and comment if needed.
> Add Select All option to most of processor & sink where applicable

- webservice/src/main/resources/app/scripts/containers/Streams/TestRunComponents/TestSourceNodeModal.jsx
- webservice/src/main/resources/app/styles/css/style.css
Integrated manual code Formatter on button click.
And delete icon color changed to (white).
@shahsank3t  please review and comment.
> ISSUE-921 Test Mode: Minor UI Improvements

- webservice/src/main/resources/app/scripts/components/TopologyGraphComponent.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TestRunComponents/EventLogContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/TopologyEditorContainer.jsx
- webservice/src/main/resources/app/styles/css/style.css
This fixes https://github.com/hortonworks/streamline/issues/924
> ISSUE-924 Test mode running into issues in Firefox browser

- streams/runners/storm/runtime/pom.xml
ISSUE-1019: Shade jackson annotation library to avoid version mismatch issue
> ISSUE-1019: Shade jackson annotation library to avoid version mismatch issue

- bootstrap/components/sinks/kafka-sink-topology-component.json
- bootstrap/components/sources/kafka-source-topology-component.json
- pom.xml
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/SchemaResource.java
Kafka source and sink leverages schema branching available with registry 0.5.0 release.
Closes #1199
> ISSUE-1199 Leverage schema branching in Kafka sources to pull schemas  from non master branches.

- streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/CustomProcessorBolt.java
- streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/CustomProcessorBoltTest.java
- streams/sdk/src/main/java/com/hortonworks/streamline/streams/runtime/SimpleCustomProcessorRuntime.java
Will raise a separate one for master.
> ISSUE-1279: Fix null handling in CustomProcessorBolt

- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/ProjectionProcessorContainer.jsx
This PR fixes https://github.com/hortonworks/streamline/issues/1293
> ISSUE-1293 Configured projection processor shows as blank

- streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java
> ISSUE-1295 Disable topology and cluster metrics consumer for test mode

- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/ProjectionProcessorContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/WindowingAggregateNodeForm.jsx
- webservice/src/main/resources/app/scripts/utils/ProcessorUtils.js
@shahsank3t  Can you please review this PR.
> ISSUE-1273 Output fields of a custom processor should honor the schema definition

- pom.xml
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyActionsService.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/StreamsModule.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyDashboardResource.java
Updated registry version to "0.5.4.3.4.0.0-96" to resolve HDF build issues, will update once again after we are done with registry release. (which should happen in couple of days)
> MINOR : Update registry version and fix transaction isolation enum

- pom.xml
- streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyActionsService.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/StreamsModule.java
- streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyDashboardResource.java
Updated registry version with 0.6.0
> Updated registry version with 0.6.0
