bin/streamline-server-start.sh, conf/streamline.mysql.yaml, conf/streamline.phoenix.yaml, conf/streamline.yaml, streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/container/TopologyActionsContainer.java, streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java
* Replace ${STREAMLINE_HOME} in streamlineStormJar to the streamline home directory
* streamline-server-start.sh finds home directory and pass via Java system property
* when streamlineStormJar is not present, it will take default path
@harshach This is updated PR of #491. Please review.
=> STREAMLINE-631 Pick runtime jar in libs dir to the default streamlineStormJar config

bootstrap/bootstrap.sh, bootstrap/components/sources/eventhubs-source-topology-component.json, streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/topology/component/bundle/impl/EventHubsSourceHintProvider.java, streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/EventHubSpoutFluxComponent.java
Added topology component definition for Event Hubs.
@harshach @shahsank3t 
When I drag and drop the component and try to edit the details, the "Cluster" field is coming out as empty since the Ambari cluster does not have a service named "EVENTHUB". Is the cluster a mandatory parameter for sources ? I am not sure how to test the eventhub component.
=> STREAMLINE-420: Change topology component definition for Eventhub to use yaml spec file

streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/AbstractProcessorBolt.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/BaseTickTupleAwareRichBolt.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/CustomProcessorBolt.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/StreamsShellBolt.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/notification/NotificationBolt.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/rules/RulesBolt.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/testing/NotificationsTestBolt.java, streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/CustomProcessorBoltTest.java
* adds TupleUtils.isTick for each Bolt implementations
I've seen some Storm Bolt implementations also don't handle tick tuples. I'll make a patch for Storm side too.
If we want to wrap the Bolt in Streamline and fix in Streamline, please let me know.
=> STREAMLINE-664 Handle tick tuples in all storm components of a streamline topology

streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/WindowedQueryBolt.java
In this :
.selectStreamLine("key1, stream1:key2")
Here there is an implicit  "streamline-event." prefix before each name : streamline-event.key1, stream1:streamline-event.key2
This patch ensures that the above case is handled correctly when we use streamname: prefix to resolve ambiguity in keynames.
=> STREAMLINE-776 - Bug fix in WindowedQueryBolt's handling of streamline event prefix in outputfields

streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/JoinBoltFluxComponent.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/WindowedQueryBolt.java, streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/TestWindowedQueryBolt.java
Note to UI devs:
Sample of JSON coming from UI to perform aliasing: See the 'as' clause in the 'outputKeys' section below:
{
"from" : {"stream": "s1", "key": "k1"},
"joins" :
[
{"type" : "left",  "stream": "s2", "key":"k2", "with": "s1"},
],
"outputKeys" : [ "k1", "s2:k2 as key2" ],
"window" : { ...... },
"outputStream" : "joinedStream1"
}
=> STREAMLINE-781  Support aliasing of output field names in WindowedQuery.selectStreamline()

bootstrap/bootstrap.sh, bootstrap/components/sinks/notification-sink-topology-component.json, bootstrap/services/email-bundle.json, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/Constants.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/NotificationSinkBundleHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/AbstractServiceRegistrar.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/DruidServiceRegistrar.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/EmailServiceRegistrar.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/HBaseServiceRegistrar.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/HDFSServiceRegistrar.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/HiveServiceRegistrar.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/KafkaServiceRegistrar.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/StormServiceRegistrar.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/register/impl/ZookeeperServiceRegistrar.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/NotificationSinkBundleSourceHintProviderTest.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/register/impl/EmailServiceRegistrarTest.java
* implements hint provider for Notification sink
* implements service registrar for Email
@shahsank3t 
I can't test it on the UI since there seems no way to provide hints for nested fields. Other bundles don't require that, so this is a new requirement.
Below is the output format which Notification hint provider will provide.
```
{
"3": {
"cluster": {
"id": 3,
"name": "EMailTest",
"ambariImportUrl": "",
"description": "EmailTest",
"timestamp": 1491991431783
},
"hints": {
"properties.host": "smtp.gmail.com",
"properties.ssl": "true",
"properties.port": "587",
"properties.protocol": "smtp",
"properties.auth": "true",
"properties.starttls": "true"
}
}
}
```
Please check and modify UI side accordingly. Thanks in advance!
=> STREAMLINE-751 Email as service option in Manual Cluster

streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/SecurityUtil.java, streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/authentication/StreamlineKerberosRequestFilter.java, streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/authentication/StreamlineSecurityContext.java, streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/impl/DefaultStreamlineAuthorizer.java, streams/sdk/src/main/java/com/hortonworks/streamline/streams/security/AuthenticationContext.java, streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyEditorToolbarResource.java, webservice/src/main/java/com/hortonworks/streamline/webservice/StreamlineApplication.java
I did some basic testing with the secure cluster and it appears to work. Need to do more testing.
When the user is not authorized, we return a 401 NotAuthorized response but UI seems to be hanging. Observed this while adding service pool.
Corresponding users for the admin principals listed in the streamline.yaml should be added via the user api before they can create entities. (E.g streamline-hdf user needs to be added in the streamline db before streamline-hdf@EXAMPLE.COM). This can be done by the same admin user.
=> STREAMLINE-787: Populate the user principal into jax-rs SecurityContext from HttpServletRequest

bootstrap/bootstrap.sh, pom.xml
This patch is needed for pulling the change from STORM-2512: Make constructor public and add one more builder constructor.
The codebase of Streamline is already changed to apply STORM-2512, and without this patch, topology submission fails.
=> Update Storm version to 1.0.2.3.0.0.0-310 to apply recent changes

bootstrap/components/sinks/kafka-sink-topology-component.json, bootstrap/components/sources/kafka-source-topology-component.json
We're using dynamic SASL jaas config which is introduced at 0.10.2.0 for Kafka sources and sinks, but storm-kafka-client pulls kafka-clients 0.10.0.0 so the configuration is ignored in runtime.
This patch will fix the issue.
=> Quick Fix: Force using kafka-clients to 0.10.2.1 to use dynamic SASL jaas config

bootstrap/bootstrap.sh, bootstrap/components/sinks/hbase-sink-topology-component.json, bootstrap/components/sinks/kafka-sink-topology-component.json, bootstrap/components/sources/kafka-source-topology-component.json, bootstrap/components/topology/storm-topology-component.json, common/src/main/java/com/hortonworks/streamline/common/ComponentTypes.java, pom.xml, streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/container/TopologyActionsContainer.java, streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/topology/component/TopologyComponentFactory.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/HBaseBundleHintProvider.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/HBaseBundleHintProviderTest.java, streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/TopologyLayoutConstants.java, streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/component/impl/HBaseSink.java, streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/component/impl/HdfsSink.java, streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/component/impl/HiveSink.java, streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/component/impl/KafkaSink.java, streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/AutoCredsServiceConfigurationReader.java, streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/ServiceConfigurationReader.java, streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java, streams/runners/storm/common/src/main/java/com/hortonworks/streamline/streams/storm/common/ServiceConfigurationReadable.java
WIP: I checked that this patch provides necessary configuration to the topology config so I think it's OK to be reviewed, but I didn't do end-to-end system test yet.
This patch is on top of #568 so please check the commits only for STREAMLINE-769.
To activate auto credential, user needs to fill out "principal" and "keytab path" in nimbus node for each cluster to the topology config. Streamline finds Cluster entity by name so user needs to fill out cluster's name as well for each cluster.
(I know filling out cluster name by user is bad but I don't know how we can provide hint for this.)
Currently HDFS and HBase are supported. Hive and Kafka should be done after getting auto-creds for Hive and Kafka.
`putAutoTokenDelegationConfig` is the main function which handles the feature.
Please refer …
=> STREAMLINE-769 Streamline changes for auto cred

bootstrap/components/sinks/hbase-sink-topology-component.json
* both log4j-over-slf4j and slf4j-log4j12 are in classpath
Change-Id: Id00d87d8a20c78ce208fa6be266ab0a214ca157f
=> Quick Fix: exclude slf4j-log4j12 from HBase maven artifacts

streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/AbstractBundleHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/ComponentBundleHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/AbstractHDFSBundleHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/DruidSinkBundleHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/EventHubsSourceHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/HBaseBundleHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/KafkaBundleHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/KafkaSinkBundleHintProvider.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/bundle/impl/NotificationSinkBundleHintProvider.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/AbstractBundleHintProviderTest.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/AbstractHDFSBundleHintProviderTest.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/DruidSinkBundleHintProviderTest.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/HBaseBundleHintProviderTest.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/KafkaBundleHintProviderTest.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/KafkaSinkBundleHintProviderTest.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/bundle/impl/NotificationSinkBundleSourceHintProviderTest.java, streams/service/src/main/java/com/hortonworks/streamline/streams/service/StreamsModule.java, streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyComponentBundleResource.java
* this is needed for getting metadata from secured cluster to build hints
* especially HBaseMetadataService and HBaseBundleHintProvider
=> Let hint provider handles SecurityContext and Subject

bootstrap/components/sinks/jdbc-sink-topology-component.json, streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/StormTopologyDependenciesHandler.java
This closes #601 
* add optional field "mavenArtifacts" to JDBC sink
* the value of the field will be added to the topology dependency
* as exactly same as topology component bundle
* other components can add "mavenArtifacts" later, and they will also be cared
Before this patch, we need to add JDBC-compatible library to the mavenDep of JDBC sink bundle manually, but after this patch we don't need to.
Manually tested.
=> ISSUE-601 Add "artifacts" feature for JDBC sink bundle

bootstrap/components/sinks/jdbc-sink-topology-component.json, streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/JDBCBoltFluxComponent.java
* since some storages including Phoenix doesn't support javax.sql.DataSource
* modify all fields to conform to driverClassName (we no longer use datasource config)
Please refer https://github.com/brettwooldridge/HikariCP for field descriptions.
=> ISSUE-604 Use DRIVER CLASS NAME in JDBC sink for as its name represents

streams/runners/storm/metrics/src/main/java/com/hortonworks/streamline/streams/metrics/storm/topology/StormTopologyMetricsImpl.java
* currently 30 secs which might give feeling a bit long
* Storm itself updates the executors metrics via heartbeat, which is by default per 3 seconds
* so 5 secs would make users feel close to real time update
Change-Id: I44dffb5f9fb1ce5d705e219ce2046279ccbf9852
=> ISSUE-637 Reduce the cache duration for Storm metrics query result

bootstrap/components/topology/storm-topology-component.json, streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/AutoCredsServiceConfigurationReader.java, streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java, streams/runners/storm/common/src/main/java/com/hortonworks/streamline/streams/storm/common/ServiceConfigurationReadable.java
This closes #693 .
@shahsank3t You can just put `clusterId` as Long (JSON default number type I guess) instead of `clusterName` in clusterSecurityConfig.
=> ISSUE-693 use "cluster id" for Cluster security config to ensure selected cluster unique

streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/TopologyTestRunHistory.java, streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/UDF.java, streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/topology/TopologyComponentBundle.java
While we get the value from CHAR(5) which contains "true" (hence 1 space left), rightmost whitespace is trimmed for MySQL but unfortunately not for PostgreSQL.
Change-Id: Iac69fea23975949d5b1a08040878943078ae5a77
=> BUG-82171 NullPointer exception when using PostgreSQL as backend storage

common/src/main/java/com/hortonworks/streamline/common/util/FileStorage.java, common/src/main/java/com/hortonworks/streamline/common/util/HdfsFileStorage.java, common/src/main/java/com/hortonworks/streamline/common/util/LocalFileSystemStorage.java, streams/service/src/main/java/com/hortonworks/streamline/streams/service/UDFCatalogResource.java
1. Log warn and throw EntityAlreadyExistsException if the UDF already exists
2. Fix the issue where the jar file was getting uploaded even if the digest match
Fixes #764
=> ISSUE-764: Remove stack trace when trying to register existing UDF

conf/streamline-dev.yaml, conf/streamline.mysql.yaml, conf/streamline.phoenix.yaml, conf/streamline.postgre.yaml, conf/streamline.yaml, streams/authorizer/src/main/java/com/hortonworks/streamline/streams/security/service/SecurityCatalogResource.java
Fixes #745 
@shahsank3t, sending a POST to "api/v1/catalog/users/current/logout" will invalidate the cookie. Checked in safari and via cUrl.
@harshach, we need to configure ambari to set `cookie.path: "/"` under servletFilters config in the generated streamline.yaml to always set cookie for "/".
=> ISSUE-745: Added logout REST endpoint

streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/HBaseMetadataService.java, streams/cluster/src/main/java/com/hortonworks/streamline/streams/cluster/service/metadata/common/OverrideHadoopConfiguration.java, streams/cluster/src/test/java/com/hortonworks/streamline/streams/cluster/service/metadata/common/OverrideHadoopConfigurationTest.java
- Set hbase.client.retries.number to max value of 3
- Refactor Hadoop configuration override to support prop values computed by functions
- Enhance unit tests
Change-Id: I5628a37813b96634cbcdd66798d8afb988757f25
=> ISSUE-796: HBase Client Retries Must be Configurable

bootstrap/bootstrap.sh, bootstrap/components/processors/rtjoin-bolt-topology-component.json, streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/JoinBoltFluxComponent.java, streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/RealtimeJoinBoltFluxComponent.java, streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/SLRealtimeJoinBoltFluxComponent.java, streams/runners/storm/layout/src/test/java/com/hortonworks/streamline/streams/layout/storm/JoinBoltFluxComponentTest.java, streams/runners/storm/layout/src/test/java/com/hortonworks/streamline/streams/layout/storm/RealtimeJoinBoltFluxComponentTest.java, streams/runners/storm/layout/src/test/java/com/hortonworks/streamline/streams/layout/storm/SLRealtimeJoinBoltFluxComponentTest.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/Cmp.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/FieldSelector.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/InvalidTuple.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/JoinComparator.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/RTJoinExampleTopology.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/RealtimeJoinBolt.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/SLCmp.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/SLRealtimeJoinBolt.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/WindowedQueryBolt.java, streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/bolt/query/TestRealtimeJoinBolt.java, webservice/src/main/resources/app/scripts/components/StreamSidebar.jsx, webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/ProcessorNodeForm.jsx, webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/SinkNodeForm.jsx, webservice/src/main/resources/app/scripts/containers/Streams/TopologyEditor/SourceNodeForm.jsx
Sample usage:
RealtimeJoinBolt bolt = new RealtimeJoinBolt(Selector.STREAM)
.dataStream("orders")
.innerJoin("ads", new BaseWindowedBolt.Duration(10, TimeUnit.SECONDS), false) // buffer each event for 10 seconds
.equal("userId", "userID" )    // join keys corresponding to the above two streams
.equal("productId", "productId" )
.select("orders:id, ads:userId, orders:product, price");
**Features:**
-  Join Types:  inner, left, right, outer
-  MultKey joins
-  Currently allows joining only two streams at a time. Can use cascaded joins for joining additional streams.
- Realtime joins and not windowed joins. Does not wait for Window expiration to occur before emitting. It buffers one of the streams and the other stream is joined with it in realtime.
=> STREAMLINE-457  Adding RealtimeJoinBolt.

webservice/src/main/resources/app/scripts/utils/Utils.js
Reader/writer schema version is being passed as int value which should be passed as a string from UI. This change resolves for both source & sink.
=> ISSUE-774: reader and writer schema value needs to passed as string

bootstrap/bootstrap-udf.sh
Renamed to `IDENTITY_FN` so that calcite does not treat it as a special keyword.
@harshach , pinging to see if this can be included in the maint release.
@shahsank3t , After applying this patch, the UI displays `IDENTITY_FN` in projection processor dropdown. UI should display the value from "displayName"
=> ISSUE-836: Fix identity function

webservice/src/main/java/com/hortonworks/streamline/webservice/StreamlineApplication.java, webservice/src/main/java/com/hortonworks/streamline/webservice/configurations/AuthorizerConfiguration.java, webservice/src/main/java/com/hortonworks/streamline/webservice/configurations/DashboardConfiguration.java, webservice/src/main/java/com/hortonworks/streamline/webservice/configurations/FileStorageConfiguration.java, webservice/src/main/java/com/hortonworks/streamline/webservice/configurations/LoginConfiguration.java, webservice/src/main/java/com/hortonworks/streamline/webservice/configurations/ModuleConfiguration.java, webservice/src/main/java/com/hortonworks/streamline/webservice/configurations/StorageProviderConfiguration.java, webservice/src/main/java/com/hortonworks/streamline/webservice/configurations/StreamlineConfiguration.java, webservice/src/main/java/com/hortonworks/streamline/webservice/resources/StreamlineConfigurationResource.java, webservice/src/main/java/com/hortonworks/streamline/webservice/util/StreamlineConfigurationSerializer.java, webservice/src/test/java/com/hortonworks/streamline/webservice/RestIntegrationTest.java
This commit contains following changes :
* Move configurations and resources under webservice to their respective directories.
* Instead of serializing StreamlineConfiguration manually abstract out serializing logic to its dedicated JsonSerializer.
=> Use custom JsonSerializer to serialize StreamlineConfiguration

streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/TopologyActions.java, streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyTestRunner.java, streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java, streams/runners/storm/actions/src/test/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyTestRunnerTest.java
* while requesting topology test run, "durationSecs" is added to config json
* the config is optional, and default value is 30 secs (up to runner implementation)
@shahsank3t 
This needs UI change that provides feature to let users input test run duration. 
UI can include the KV of config to the JSON: key name is "durationSecs", and unit is second.
(For type of value, you can just pick the same type as what you use to provide `testCaseId`.)
If the config doesn't exist in json, it will be run with default value (same as it is).
=> ISSUE-860 Add timeout option to topology test run

streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/TopologyActions.java, streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyActionsService.java, streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyTestRunner.java, streams/runners/storm/actions/src/main/java/com/hortonworks/streamline/streams/actions/storm/topology/StormTopologyActionsImpl.java, streams/runners/storm/actions/src/test/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyTestRunnerTest.java, streams/service/src/main/java/com/hortonworks/streamline/streams/service/TopologyTestRunResource.java
* add new REST API endpoint: force stop running test
* /topologies/{topologyId}/actions/killtest/{historyId}
* it just turns on the flag to force stop, and return immediately
* response with OK would be {"flagged": true/false}
* flagged will be 'true' only when process is running now and 'false' otherwise so it doesn't indicate request has been failed
* let 'test run' handles force stop flag and destroy process if flag is turned on
This closes #899 
As I also noted to https://github.com/hortonworks/streamline/issues/899#issuecomment-327700819, please keep it mind that 'force stop' will make test run marked as 'failed'.
=> ISSUE-899 Test mode: Provide an option to force stop a test run

bootstrap/sql/mysql/v003__add_sleep_iteration_to_topology_test_run_case_source.sql, bootstrap/sql/postgresql/v003__add_sleep_iteration_to_topology_test_run_case_source.sql, streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyTestRunner.java, streams/catalog/src/main/java/com/hortonworks/streamline/streams/catalog/TopologyTestRunCaseSource.java, streams/layout/src/main/java/com/hortonworks/streamline/streams/layout/component/impl/testing/TestRunSource.java, streams/runners/storm/actions/src/test/java/com/hortonworks/streamline/streams/actions/storm/topology/TestTopologyDagCreatingVisitorTest.java, streams/runners/storm/actions/src/test/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyTestRunnerTest.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/testing/TestRecordsInformation.java, streams/runners/storm/runtime/src/main/java/com/hortonworks/streamline/streams/runtime/storm/testing/TestRunSourceSpout.java, streams/runners/storm/runtime/src/test/java/com/hortonworks/streamline/streams/runtime/storm/testing/TestRecordsInformationTest.java
* add option regarding sleep per iteration in TopologyTestRunCaseSource
* apply TestRunSourceSpout to respect sleep per each output stream
* add SQL script to apply the change of table
@shahsank3t 
The change is introduced into TopologyTestRunCaseSource. UI just needs to add `sleepMsPerIteration` when requesting to add/update TopologyTestRunCaseSource. Unit is millisecond.
No new API endpoint, and default value is 0L.
@arunmahadevan Please take a look and comment. Thanks in advance.
=> ISSUE-902 Add a sleep option along with repeat count

streams/actions/src/main/java/com/hortonworks/streamline/streams/actions/topology/service/TopologyTestRunner.java
* this change ensures that empty event will be available immediately when UI gets response
This closes #901.
Please refer my comment on #901. Although this doesn't go with suggested way in #901, I guess this patch resolves the origin issue simpler.
@shahsank3t UI can call /events immediately after receiving response of request for test run. It would be empty event indeed.
@arunmahadevan @shahsank3t Please review and comment. Thanks in advance!
=> ISSUE-901 Test mode: Create event file prior to launch actual test process

DEVELOPER.md, dev-tools/merge_streamline_pr.py
* introduce merge script which is based on Spark merge script and borrow some block from Kafka
* removed unnecessary parts regarding porting back, handling JIRA issues including marking versions
This closes #923 but need to remove CHANGELOG.md separately since including removal of CHANGELOG.md will incur merge conflict.
Please play with merge script to determine how it works and how it configures commit title and commit message of squashed commit.
The script is not that complicated if you are familiar with git command so you may want to also read the script.
=> ISSUE-923 Improve the commit process and remove the CHANGELOG

webservice/src/main/resources/app/scripts/utils/ProcessorUtils.js
If the function doesn't have the returnType than the field's type will take the precedence, And if it has then it will be the return Type i:e 
1] Function "SUM" doesn't have the return Type then field type will be the function return type.
3] Function "COUNT".... the function return Type will be the default one.
@arunmahadevan  verify on your side as well, thanks in advanced
=> ISSUE-1291 SAM Aggregate processor output schema types are wrong
